### ISSUE TITLE
Uncaught TypeError: Cannot read property 'boot' of null

### ISSUE THREAD

**Issue by jrmaher** [aminya/juno-plus#13]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 7 Home Premium 
**Thrown From**: [juno-plus](https://github.com/aminya/juno-plus) package 0.12.2

### Stack Trace

Uncaught TypeError: Cannot read property 'boot' of null

```
At C:\Users\Joe\.atom\packages\juno-plus\lib\juno-plus.js:100

TypeError: Cannot read property 'boot' of null
    at /packages/juno-plus/lib/juno-plus.js:100:25)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:349538)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:348013)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/items/tool-bar-button-view.js:153:23)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/items/tool-bar-button-view.js:127:12)
```

### Commands

```
     -2:46.9.0 command-palette:toggle (input.hidden-input)
     -2:41.4.0 editor:consolidate-selections (input.hidden-input)
     -2:41.4.0 core:cancel (input.hidden-input)
     -2:23.2.0 juno-plus:Revise (input.hidden-input)
```

### Non-Core Packages

```
atom-julia-run 1.0.5 
busy-signal 2.0.1 
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.12.3 
intentions 1.1.5 
julia-client undefined 
julia-ide 0.3.0 
juno-plus 0.12.2 
language-julia 0.19.3 
latex-completions 0.3.6 
linter 2.3.1 
linter-julia 0.8.3 
linter-ui-default 1.8.1 
markdown-pdf 2.3.3 
tool-bar 1.3.0 
uber-juno 0.3.0 
```

**Comment by aminya** [comment]
When does this happen? I cannot reproduce it.

**Comment by HerClau** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [juno-plus](https://github.com/aminya/juno-plus) package 0.12.2


### Stack Trace

Uncaught TypeError: Cannot read property 'boot' of null

```
At C:\Users\user\.atom\packages\juno-plus\lib\juno-plus.js:100

TypeError: Cannot read property 'boot' of null
    at /packages/juno-plus/lib/juno-plus.js:100:25)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:349781)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:348256)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/items/tool-bar-button-view.js:153:23)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/items/tool-bar-button-view.js:127:12)
```

### Commands

```
  2x -3:05.8.0 editor:join-lines (atom-pane.pane.active)
     -1:27.5.0 juno-plus:Revise (div.welcome.is-guide)
```

### Non-Core Packages

```
cobalt2-syntax 0.5.3 
cobolt-atom-theme 0.3.3 
indent-detective 0.4.0 
ink 0.12.4 
julia-client undefined 
juno-plus 0.12.2 
kobalt 0.7.1 
kobalt-ui 0.5.1 
language-julia 0.19.3 
latex-completions 0.3.6 
seti-ui-red 0.13.0 
tool-bar 1.3.0 
uber-juno 0.3.0 
```
