### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of null

### ISSUE THREAD

**Issue by asgherali39** [aminya/juno-plus#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Education
**Thrown From**: [juno-plus](https://github.com/aminya/juno-plus) package 0.10.2

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of null

```
At C:\Users\Asgher Ali\.atom\packages\juno-plus\lib\juno-plus.coffee:60

TypeError: Cannot read property 'then' of null
    at /packages/juno-plus/lib/juno-plus.coffee:60:7)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:349290)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.44.0/resources/app/static/<embedded>:11:347765)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:139:23)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:113:12)
```

### Commands

```
     -0:14.5.0 juno-plus:restart-julia (ul.list-inline.tab-bar.inset-panel)
     -0:14.5.0 julia-client:kill-julia (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-julia-run 1.0.5 
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.12.2 
julia-client undefined 
juno-plus 0.10.2 
language-julia 0.19.2 
language-juniper-junos 1.0.0 
language-junos 0.0.2 
latex-completions 0.3.6 
rest-client 1.3.1 
tool-bar 1.2.0 
uber-juno 0.3.0 
youtube-pane 2.0.0 
```

**Comment by aminya** [comment]
I cannot reproduce this. Try uninstalling julia client and ink and reinstalling them. Your Julia client version is shwon as undefined...!

**Comment by aminya** [comment]
Atom gets hanged sometimes (in recent versions). I don't know what has changed in Atom or Julia Client that causes this.

**Comment by aminya** [comment]
Juno-Plus part of the issue is resolved, but the upstream issue still isn't fixed https://github.com/JunoLab/Juno.jl/issues/510

**Comment by HerClau** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [juno-plus](https://github.com/aminya/juno-plus) package 0.12.2


### Stack Trace

Uncaught TypeError: Cannot read property 'then' of null

```
At C:\Users\user\.atom\packages\juno-plus\lib\juno-plus.js:90

TypeError: Cannot read property 'then' of null
    at /packages/juno-plus/lib/juno-plus.js:90:21)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:349781)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:348256)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/items/tool-bar-button-view.js:153:23)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/items/tool-bar-button-view.js:127:12)
```

### Commands

```
  5x -4:02.9.0 core:backspace (input.hidden-input)
  2x -2:12.4.0 editor:auto-indent (div.package-detail)
  3x -2:09.9.0 juno-plus:toggle-folding (div.package-detail)
  3x -2:04.5.0 julia:new-julia-file (div.package-detail)
  2x -1:51.1.0 julia-client:interrupt-julia (ul.list-inline.tab-bar.inset-panel)
     -1:20.1.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -1:07.0 juno-plus:restart-julia (ul.list-inline.tab-bar.inset-panel)
     -1:07.0 julia-client:kill-julia (atom-workspace.workspace.scrollbars-visible-always.theme-cobolt-atom-theme.theme-kobalt-ui)
     -0:59.8.0 markdown-preview:toggle (atom-pane.pane.active)
  2x -0:55.4.0 julia-client:run-all (atom-pane.pane.active)
     -0:52.8.0 julia-client:run-and-move (atom-pane.pane.active)
     -0:51.2.0 juno-plus:restart-julia (atom-pane.pane.active)
     -0:51.2.0 julia-client:kill-julia (atom-workspace.workspace.scrollbars-visible-always.theme-cobolt-atom-theme.theme-kobalt-ui)
```

### Non-Core Packages

```
atom-julia-run 1.0.5 
atom-material-ui 2.1.3 
cobalt2-syntax 0.5.3 
cobolt-atom-theme 0.3.3 
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.12.4 
julia-client undefined 
juno-plus 0.12.2 
kobalt 0.7.1 
kobalt-ui 0.5.1 
language-julia 0.19.3 
latex-completions 0.3.6 
seti-ui-red 0.13.0 
tool-bar 1.3.0 
uber-juno 0.3.0 
```
